In [1]:
import numpy as np

In [11]:
m = np.array([[1,4],[2,4],[3,9],[4,16]])
print(np.dot(m.T,m))
print(np.dot(m,m.T))

[[ 30 103]
 [103 369]]
[[ 17  18  39  68]
 [ 18  20  42  72]
 [ 39  42  90 156]
 [ 68  72 156 272]]


In [19]:
mm = np.dot(m.T,m)
print(mm)
print(np.linalg.eig(mm))

[[ 30 103]
 [103 369]]
(array([  1.15875366, 397.84124634]), array([[-0.96296099, -0.26964073],
       [ 0.26964073, -0.96296099]]))


In [20]:
mmt = np.dot(m,m.T)
print(mmt)
print(np.linalg.eig(mmt))

[[ 17  18  39  68]
 [ 18  20  42  72]
 [ 39  42  90 156]
 [ 68  72 156 272]]
(array([ 3.97841246e+02,  1.15875366e+00, -5.98858961e-15,  1.83747803e-15]), array([[-0.20663258,  0.1073914 ,  0.9407655 ,  0.01587037],
       [-0.22015114, -0.78717614, -0.10679013,  0.57527444],
       [-0.47506222, -0.429295  ,  0.14238684, -0.76703259],
       [-0.8265303 ,  0.42956561, -0.28858644,  0.28366963]]))


In [21]:
a = np.array([[1,1],[1,1],[0,0]])
print(np.dot(a,a.T))
print(np.dot(a.T,a))

[[2 2 0]
 [2 2 0]
 [0 0 0]]
[[2 2]
 [2 2]]


In [26]:
U,sigma,VT=np.linalg.svd(np.dot(a,a.T))
print (U)
print (sigma)
print (VT)

[[-0.70710678  0.         -0.70710678]
 [-0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]]
[4. 0. 0.]
[[-0.70710678 -0.70710678 -0.        ]
 [ 0.          0.          1.        ]
 [-0.70710678  0.70710678  0.        ]]


In [27]:
U,sigma,VT=np.linalg.svd(np.dot(a.T,a))
print (U)
print (sigma)
print (VT)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[4. 0.]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
